# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=200)),
                ('pud_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
