# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='sub_header_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
