# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_header_sub_header_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='pud_date',
        ),
    ]
