# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_header_pud_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='choose',
            field=models.IntegerField(default=1),
        ),
    ]
