# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_header_choose'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_sub_title', models.CharField(max_length=200)),
                ('post_context', models.CharField(max_length=6000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='header',
            name='choose',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'About'), (3, 'Contact')], default=1),
        ),
    ]
