# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='news',
            name='post_context',
            field=models.TextField(),
        ),
    ]
