# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170821_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='current_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(),
        ),
    ]
